# Generated by Django 4.1 on 2023-12-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
